apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "RemovePodsViolatingTopologySpreadConstraint":
     enabled: true
     params:
       nodeFit: true
       includeSoftConstraints: true # Include 'ScheduleAnyways' constraints
